name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox

      - name: Test with nox
        run: |
          nox --sessions=tests --python=${{ matrix.python-version }}

  docs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Set up packages
        run: sudo apt-get install pandoc
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox

      - name: Test with nox
        run: |
          nox --sessions=docs-build


  #     - name: Coverage
  #       uses: codecov/codecov-action@v2

  # deploy:
  #   needs: [test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python 3.10
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: "3.10"

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         python -m pip install poetry

  #     - name: Bump version and build
  #       run: |
  #         poetry version patch &&
  #         version=$(poetry version | awk '{ print $2 }') &&
  #         poetry version $version.dev.$(date +%s) &&
  #         poetry build

  #     - name: Release on TestPyPI
  #       uses: pypa/gh-action-pypi-publish@v1.4.2
  #       with:
  #         user: __token__
  #         password: ${{ secrets.TEST_PYPI_TOKEN }}
  #         repository_url: https://test.pypi.org/legacy/
